name: React CICD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        run: sudo timedatectl set-timezone America/Chicago
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.0.0"
      - name: Install npm
        run: npm install -g npm@7.10.0
      - name: Install Dependencies
        run: npm install
      - name: Compile Project
        run: npm run build
      - name: Test Project
        run: npm test
